# Generated by Django 4.1 on 2022-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersmaster',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersmaster',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersmaster',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
