# Generated by Django 4.1 on 2022-09-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_alter_teachersmaster_dob_alter_teachersmaster_doj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersmaster',
            name='org',
        ),
    ]
