# Generated by Django 4.1 on 2022-09-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_remove_teachersmaster_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardmaster',
            name='classTeacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.teachersmaster'),
        ),
        migrations.AlterField(
            model_name='standardmaster',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='standardmaster',
            name='updatedBy',
            field=models.CharField(max_length=40),
        ),
    ]
