# Generated by Django 4.1 on 2022-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(max_length=12, null=True, unique=True, verbose_name='Mobile'),
        ),
    ]
