# Generated by Django 4.1 on 2022-08-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='admin_portal.student'),
        ),
    ]
