# Generated by Django 4.1 on 2022-08-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodmaster',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.hod'),
        ),
        migrations.AddField(
            model_name='teachersmaster',
            name='empNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
