# Generated by Django 4.1 on 2022-08-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_hodmaster_hod_teachersmaster_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmaster',
            name='orgUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.org'),
        ),
        migrations.AlterField(
            model_name='hodmaster',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.hod'),
        ),
        migrations.AlterField(
            model_name='hodmaster',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.organizationmaster'),
        ),
    ]
