# Generated by Django 4.1 on 2022-08-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_organizationmaster_orguser_alter_hodmaster_hod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodmaster',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to='admin_portal.hod'),
        ),
        migrations.AlterField(
            model_name='hodmaster',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='admin_portal.organizationmaster'),
        ),
        migrations.AlterField(
            model_name='organizationmaster',
            name='orgUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_user', to='admin_portal.org'),
        ),
    ]
