# Generated by Django 4.1 on 2022-08-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_alter_hodmaster_hod_alter_hodmaster_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmaster',
            name='orgUser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgUser', to='admin_portal.org'),
        ),
    ]
